"""init_all

Revision ID: a9ff7958a976
Revises: 
Create Date: 2026-08-31 18:12:19.715573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9ff7958a976'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventmodel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('page', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('referrer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'time')
    )
    op.create_index(op.f('ix_eventmodel_page'), 'eventmodel', ['page'], unique=False)
    op.create_index(op.f('ix_eventmodel_country'), 'eventmodel', ['country'], unique=False)
    op.create_index(op.f('ix_eventmodel_ip_address'), 'eventmodel', ['ip_address'], unique=False)
    op.create_index(op.f('ix_eventmodel_referrer'), 'eventmodel', ['referrer'], unique=False)
    op.create_index(op.f('ix_eventmodel_session_id'), 'eventmodel', ['session_id'], unique=False)
    op.create_index(op.f('ix_eventmodel_user_agent'), 'eventmodel', ['user_agent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventmodel_user_agent'), table_name='eventmodel')
    op.drop_index(op.f('ix_eventmodel_session_id'), table_name='eventmodel')
    op.drop_index(op.f('ix_eventmodel_referrer'), table_name='eventmodel')
    op.drop_index(op.f('ix_eventmodel_ip_address'), table_name='eventmodel')
    op.drop_index(op.f('ix_eventmodel_country'), table_name='eventmodel')
    op.drop_table('eventmodel')
    # ### end Alembic commands ###
